### PR TITLE
Provide __all__ for tuf.ngclient module

### PR DESCRIPTION
**Pull request by fridex**
**Description of the changes being introduced by the pull request**:

Document public API for `tuf.ngclient` module.

### CODE REVIEW

**Comment by fridex** [comment]
It looks like the public API is not documented in the whole python-tuf project. Would community be interested in providing `__all__` to explicitly document exported API (I can try to find some time to work on it)?

**Comment by fridex** [comment]
Superseded by #2234.

**Comment by fridex** [comment]
Reopening based on discussion in https://github.com/theupdateframework/python-tuf/issues/2235#issuecomment-1357332357

**Review by jku — APPROVED** [review]
I'm ok with this: I think the API does not change at all here (since the default is that "import *" gives you everything in `__init__.py`) but I think being explicit is fine.

Other further API clarifications we could do:
* export TargetFile along with Updater here (as it's a major part of Updater API)
* rename updater.py into `_updater.py` to make the API crystal clear

the first of those seems obviously correct... the second one is on the edge of "is it worth the unlikely but possible breakage"

**Pull request merged**
