### PR TITLE
Remove specific adoptions from README

### PR DESCRIPTION
**Pull request by trishankkarthik**
**Fixes issue #**:

As per https://github.com/theupdateframework/theupdateframework.io/pull/10

**Description of the changes being introduced by the pull request**:

Update list of adoptions

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by joshuagl** [comment]
LGTM. The DCO checks are failing because none of the commit headers have a Signed-off-by line

**Comment by JustinCappos** [comment]
It seems a bit extreme to delete the adopters list from both the README and
the ADOPTERS.md from the site.  I'd prefer we update the content to make it
more accurate instead...

**Comment by trishankatdatadog** [comment]
> It seems a bit extreme to delete the adopters list from both the README and the ADOPTERS.md from the site. I'd prefer we update the content to make it more accurate instead...

The problem is in maintaining more than one source of truth for adoptions: one on theupdateframework.io and here. Seems best to maintain one well-curated one...

**Comment by JustinCappos** [comment]
> > It seems a bit extreme to delete the adopters list from both the README and the ADOPTERS.md from the site. I'd prefer we update the content to make it more accurate instead...
> 
> The problem is in maintaining more than one source of truth for adoptions: one on theupdateframework.io and here. Seems best to maintain one well-curated one...

Got it.  Makes sense to me.

**Review by JustinCappos — APPROVED** [review]
LGTM

**Comment by trishankatdatadog** [comment]
> Got it. Makes sense to me.

I can't merge because some flaky tests prevent me. Please feel free to merge, thanks!

**Pull request merged**
