### PR TITLE
fix:  ngclient: temp_file could be undefined #1999

### LINKED ISSUE #1999: ngclient: temp_file could be undefined
From sonatype lift results: 

> Local variable temp_file is undefined, or not always defined.
> tuf/ngclient/updater.py 290:15

This seems like it could happen if NamedTemporaryFile() fails to create a file.

### PR DESCRIPTION
**Pull request by dhavalgshah**
Fixes ngclient: temp_file could be undefined #1999

Signed-off-by: Dhaval Shah <30974879+dhavalgshah@users.noreply.github.com>

Fixes #1999

### CODE REVIEW

**Comment by dhavalgshah** [comment]
Logs are empty for the failed CI run and tox is running fine on my machine as well as on other CI runs.

Is there any hint on what might have gone wrong here? @jku

**Comment by lukpueh** [comment]
If you scroll through the list of checks below, you'll find the job that failed. Its log tells you what went wrong.

**Comment by jku** [comment]
Unfortunately a lot of the python base library  predates type annotations: you likely can't annotate temp_file in a useful way.

**Review by jku — APPROVED** [review]
It's annoying that we have to make code like this more complicated... but I can't see a way to avoid it either.

Thanks, looks good to me.

**Pull request merged**
