### PR TITLE
GitHub CI workflow: tweak names

### PR DESCRIPTION
**Pull request by jku**
Currently the github UI dropdown for checks looks useless since every check is named "Run TUF tests and...". Tweak the workflow and job names to hopefully fit the actual step name in the UI.

Also start using python 3.x for lint since pylint now supports it.

Signed-off-by: Jussi Kukkonen <jkukkonen@vmware.com>

### CODE REVIEW

**Review by joshuagl — APPROVED** [review]
👍 thanks for fixing the Python version too

**Comment by jku** [comment]
> Required statuses must pass before merging

Hmm, I think the job id may be used in some branch protection rules... I should maybe try not changing the id and just change the name so we don't have to edit the rules

**Review by trishankatdatadog — APPROVED** [review]

**Comment by jku** [comment]
I've tried with with the old job id, that doesn't help: the required statuses aren't marked as passed. I think someone with permissions to do so has to play with the branch protection settings: possibly disable the required status checks, merge this PR, then enable them with the new job id/name after merging

(also the coveralls failure seems to be a botched maintenance break: they are 100% down)

**Comment by joshuagl** [comment]
Merged and required status checks have been updated to all of the "Tests" apart from with-sslib-master

**Comment by trishankatdatadog** [comment]
> ## Pull Request Test Coverage Report for [Build 1246248090](https://coveralls.io/builds/42956759)

Why on Earth are we getting an update for this now?

**Pull request merged**
