### PR TITLE
Do dependabots job

### PR DESCRIPTION
**Pull request by jku**
Here's a bunch of dependency updates we never heard of before this.

I'm filing a related issue about dependabot being broken.

### CODE REVIEW

**Comment by jku** [comment]
I guess I should mention: I didn't just play dependabot here, I did look at the changes they look fine to me.

**Comment by lukpueh** [comment]
Where do these commits come from?

**Comment by jku** [comment]
I added a fake setup.py in my own fork and configured dependabot to run there.

**Comment by lukpueh** [comment]
Oh, should have looked at new issues first, before asking questions about new prs :) --> #1828

**Review by lukpueh — APPROVED** [review]
LGTM (based on skimming the corresponding changelog entries and passing ci/cd)

**Pull request merged**
