### PR TITLE
Refactor ci/cd workflows to make more robust

### LINKED ISSUE #1961: ci/cd: make workflow pipeline more robust
**Description of issue or feature request**:
#1946 adds a CD workflow to release build artifacts on PyPI and GH upon successful completion of the CI workflow for a pushed release tag.

Unfortunately, the information about CI that we can access from CD is [vague](  https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run
) and thus makes the workflow pipeline a bit brittle (see details below). 

**Current behavior**:
CD triggers for each completed run of CI, regardless of the ref that triggered CI, but then skips execution if the CI run was not successful or the ref (branch or tag) that triggered CI does not start with a 'v'. In order to not trigger CD for a branch that starts with 'v', we rely on the configuration of CI, which currently does not trigger on other branches than 'develop'. 

**Expected behavior**:
CD triggers for completed and successful run of CI but only if CI was triggered by a release tag, regardless of CIs trigger conditions.

**Alternative solution**:
Restructure workflows, so that all test logic from 'ci.yml' is moved to a separate workflow file '_test.yml', that can be included in both the CI workflow, which then only triggers on push to 'develop'-branch, and the CD workflow, which then only triggers on on push to 'v*'-tag.

### LINKED ISSUE #1969: cd: workflow could have a permissions section
**Current behavior**:
https://github.com/theupdateframework/python-tuf/pull/1946 adds a CD workflow to release build artifacts on PyPI and GH upon successful completion of the CI workflow for a pushed release tag.

The newly added workflow does not yet configure  [`permissions`](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs).

**Current behavior**:
No permission config in cd.yml

**Expected behavior**:
Permission config cd.yml

### PR DESCRIPTION
**Pull request by lukpueh**
Fixes #1961,
Fixes #1969 

*I recommend reviewing commit by commit!*

**Description of the changes being introduced by the pull request**:

Prior to this change, ci triggered cd depending on the event that triggered ci. Due to the vague information about that event available to cd, the workflow pipeline was a bit brittle. This change disassociates ci and cd workflows to allow for an independent configuration of trigger events. The test jobs, which used to be defined in ci, are now in a separate workflow file _test.yml that can be included in both ci and cd workflows.

**Changes in ci**
- Only defines trigger events and permissions, the "meat" of ci is defined in the called _test.yml now.
- No longer triggers on tag pushes, this was only needed for cd.

**Changes in cd**
- Now triggers directly on tag pushes instead of (cd)-workflow_run.
- Calls _test.yml, and require successful run before build/release. (`needs: test` replaces `if: ...`)
- Changes variable names about pushed tag that triggered the event.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by lukpueh** [comment]
Looks like we need to update the required checks in the repo settings, because the names of jobs have changed with this PR.

We also need allow 3rd-party actions for the CD workflow until we fix #1967.

**Comment by lukpueh** [comment]
Also note that CD is still triggered by each CI run, and fails due to the 3rd-party action permission issue, even if its execution would be skipped based on what triggered ci: https://github.com/theupdateframework/python-tuf/actions/workflows/cd.yml

After this PR CD is really only triggered on tag push.

**Review by joshuagl — APPROVED** [review]
Very nice cleanup, thanks!

**Review by jku — APPROVED** [review]
Looks good, I have nothing to add.

**Comment by lukpueh** [comment]
Thanks for the reviews, I rebased and force pushed to (auto-)resolve a conflict. See note about non-completed checks above https://github.com/theupdateframework/python-tuf/pull/1971#issuecomment-1106204097.

Will merge and update required checks.

**Pull request merged**
