### PR TITLE
Refactor to use changed format metadata to key

### PR DESCRIPTION
**Pull request by MVrachev**
**Fixes issue #**:
This pr enables tuf to use changes made in https://github.com/secure-systems-lab/securesystemslib/pull/227
**Don't merge before the above pr is merged!**

**Description of the changes being introduced by the pull request**:

Because of issue https://github.com/secure-systems-lab/securesystemslib/pull/227
I had to checkout to the last commit which doesn't had that issue and
make the current changes based on it.

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by MVrachev** [comment]
I made changes to this pr, but in order to tests those changes a new version of securesyslib should be published adding the changes in the format_metadata_to_key.

**Comment by joshuagl** [comment]
Thanks for the update @MVrachev. I see the with-sslib-master failures are related to another PR you've submitted #1072, thank you for that.

**Comment by joshuagl** [comment]
Note: #1103 introduces an additional call to `format_metadata_to_key` which we should clean up in this PR if #1103 is merged first.

**Comment by MVrachev** [comment]
I rebased on the recent changes in the develop branch and the tests should no longer fail, but I don't know why `tox -e py37` fails...
Can somebody from the maintainers restart Travis CI?

**Comment by joshuagl** [comment]
Hi @MVrachev. With the release of securesystemslib 0.16.0 we are ready to include this change. Could you rebase this on the latest develop branch and when doing so edit setup.py to bump the minimum version of securesystemslib in `install_requires`?

We should also stop passing `default_keyid=None` to `securesystemslib.keys.format_metadata_to_key` as that is already the default value and we can save ourselves a line of code for each invocation of `format_metadata_to_key`. 😄

**Comment by MVrachev** [comment]
Rebased upon the latest changes in tuf and bumped securesyslib to 0.16.0 in `setup.py`.

**Review by joshuagl — APPROVED** [review]
Thank you!

**Pull request merged**
