### PR TITLE
Modernise packaging configuration

### LINKED ISSUE #1161: Modernise and rationalise packaging
**Description of issue or feature request**:

Python packaging has changed significantly since the tuf packaging was created. There's been a move to declarative files, the formalisation of build system independent source tree layout in [PEP 517](https://www.python.org/dev/peps/pep-0517/), and the addition of new metadata to specify the build system dependencies in [PEP 518](https://www.python.org/dev/peps/pep-0518/).

Furthermore our current packaging is somewhat ad-hoc, with some expected files like LICENSE missing from the sdist (see #1160) and some unexpected files like tuf/ATTACKS.md included.

For reference see:
https://packaging.python.org/
https://snarky.ca/what-the-heck-is-pyproject-toml/

**Current behavior**:

Packaging isn't up-to-date with PyPA recommendations and our sdist includes files which don't match conventions.

**Expected behavior**:

Packaging is in line with current PyPA best practices and generated distributions match ecosystem conventions.

### PR DESCRIPTION
**Pull request by joshuagl**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #1161 

A grab-bag of modernisation in our packaging

**Description of the changes being introduced by the pull request**:
* Move from invoking setup.py to build dists to instead using the `build` tool (adds `pyproject.toml`)
* Move setuptools metadata from the dynamic setup.py file to setup.cfg (removes `setup.py` completely)
* Add build and release dependencies to requirements-dev (build, wheel and twine packages)
* Include documentation link in project_urls
* update docs/RELEASE.md for packaging changes

**Note**: our sdist is effectively everything except the very few CI related files (.github/*, .fossa.yml, .readthedocs.yaml) – we could prune this back to be only the source we need to produce the wheel, but that is probably later work after we've cleaned up the documentation we keep in the repo (see #808)

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by joshuagl** [comment]
@sechkova you started looking into this in #1161, could you review the changes here?

**Comment by jku** [comment]
oops, _with-sslib-master_ uses python3.x and failure means whole build failure... and github seems to have switched to 3.10 by default. #1628 should fix the immediate issue

I think having a build that uses default python is good, but whether _with-sslib-master_ should break build is debatable

**Review by sechkova — COMMENTED** [review]
The changes look good but there was one caveat that we've discussed in the initial issue related to editable installs (https://github.com/theupdateframework/python-tuf/issues/1161#issuecomment-763473616). 
Unless it was resolved by now keeping a minimal `setup.py` may still be needed.

**Comment by joshuagl** [comment]
Thanks for the review! I think that the issue was resolved. With pip 21.2.4 here I can `pip install -e ~/Projects/python-tuf` with the branch above.
Out Tox configuration also [installs python-tuf in editable mode](https://github.com/theupdateframework/python-tuf/blob/69eb29fc80cd186b665692079b5aaf00872af558/tox.ini#L25) without failures in CI.

**Comment by sechkova** [comment]
> Thanks for the review! I think that the issue was resolved. With pip 21.2.4 here I can `pip install -e ~/Projects/python-tuf` with the branch above.
> Out Tox configuration also [installs python-tuf in editable mode](https://github.com/theupdateframework/python-tuf/blob/69eb29fc80cd186b665692079b5aaf00872af558/tox.ini#L25) without failures in CI.

Got it, my pip version seems to be older!

**Review by sechkova — APPROVED** [review]

**Pull request merged**
