### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by abs007**
Fixed a comment in utils.py

### CODE REVIEW

**Review by rdimitrov — APPROVED** [review]
Thanks, @abs007 👍 💯

**Review by MVrachev — APPROVED** [review]

**Comment by jku** [comment]
Thanks! I would prefer to get a single commit (now there's three commits for a simple comment change).

Would you like to squash to a single commit and force push? Alternatively I could use the squash-and-merge button but I'm not 100% sure if that preserves your author/committer info.

**Comment by abs007** [comment]
Made the changes :)

**Review by jku — APPROVED** [review]
Thanks!

**Pull request merged**
