### PR TITLE
Fixes #1526

### LINKED ISSUE #1526: ngclient: persist metadata in a safer way
tuf/ngclient/updater.py: `Updater._persist_metadata()`:

        with open(os.path.join(self._dir, f"{rolename}.json"), "wb") as f:
            f.write(data)

this is not as safe as it should be (as file could be corrupted midway through). This should work:
* write content to tempfile
* use `sslib_util.persist_temp_file()` to move tempfile to correct filepath

### PR DESCRIPTION
**Pull request by suvadityamuk**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #1526 

**Description of the changes being introduced by the pull request**:
Updated _persist_metadata() according to instructions in #1526 

**Please verify and check that the pull request fulfills the following
requirements**:

- [ Checked] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [Checked ] Tests have been added for the bug fix or new feature: Passes all local tests
- [Not applicable ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by suvadityamuk** [comment]
I somehow can't get this DCO thing completed. I have given the commit message accordingly but still it does not recognise or approve it

**Comment by jku** [comment]
Thanks!

That DCO complaint is a bit strange... I think maybe it's getting confused by the first commit which you maybe made with github web ui unlike the other commits. There's some minor comments so we could see if DCO is still an issue after those:
* Could you squash the commits to a single commit? Now there are two commits with just whitespace changes
* The commit title could be more informative (something like "ngclient: persist metadata using a temp file")

All the nitpicks aside... I'm now wondering if my original advice is correct. I read` securesystemslib.persist_temp_file()` and it does not look like an atomic operation as I expected :( I'll have a closer look and get back to you: _no need to improve this PR before that_.

**Comment by suvadityamuk** [comment]
Should I make a fresh PR? To see if this DCO problem gets solved then?
This is what Actions is telling me is the problem
image

**Comment by jku** [comment]
> Should I make a fresh PR? To see if this DCO problem gets solved then?
> This is what Actions is telling me is the problem
> image

That looks like what I suspected: the committer info in that one commit (unlike the other two) looks like it was maybe created in github UI? possibly you later added the signed-off-by to that commit with a (seemingly) different email address and the DCO checker is now confused.

Creating a new PR won't help but using just a single new commit with all the changes in it should work...  but don't spend a lot of your time polishing this yet: as I mentioned my original advice may have been wrong -- We're trying to make sure the final write is safe and atomic and I thought `persist_temp_file()` is but that might not actually be the case

**Comment by suvadityamuk** [comment]
Okay, understood. I'll stand by till then

**Comment by jku** [comment]
I've added my new opinion on how to solve this in #1526 (sorry for misleading in the original issue description). My earlier comments on commit structure also still stand.

**Comment by suvadityamuk** [comment]
Understood. I'll make the changes accordingly. Could you assign this task?

**Pull request closed without merging**
