### PR TITLE
update python annotations

### LINKED ISSUE #2722: update container annotations
Once #2721 is merged, we could require python 3.8 and use the nicer annotations and features. Known improvements:
* annotations for standard collections: `dict` instead of `typing.Dict`
* dict unions (I believe we have at least one place where this would be useful)

Vague process:
* bump requires-python in pyproject.toml
* run `ruff check --fix --unsafe-fixes tuf tests examples`
* review that changes made by ruff are sensible
* check if RootVerificationResult `signed()` and `unsigned()` work with a dict union -- this step could be left to another PR
* make sure `tox -e lint` and `tox -e test` pass

### PR DESCRIPTION
**Pull request by NicholasTanz**
**Description of the changes being introduced by the pull request**:

Fixes #2722

### CODE REVIEW

**Comment by NicholasTanz** [comment]
Hi @jku, when you have a moment, could you take a look at this PR. thanks

**Comment by jku** [comment]
Sorry, I've been distracted. This seems good but I'll take a closer look this week.

_Maybe_ I'll also check with some downstream users if bumping minimum python is ok with them or if we need to still wait a bit before merging...

**Comment by NicholasTanz** [comment]
No worries, thank you for reviewing my PRs! Let me know if there's anything I can do to help

**Review by kairoaraujo — APPROVED** [review]

**Comment by kairoaraujo** [comment]
Thank you @NicholasTanz for the PR

LGTM (it was on my TODO list too)

I will let @jku look at it before I merge it.

**Comment by jku** [comment]
Thanks a lot, sorry for delays. 

I might still add a from `__future__ import annotations`  before next release (since it would not break compat with 3.8 and will give us even more nice annotations from 3.10) but I think this PR is good either way

**Pull request merged**
