### PR TITLE
Rename variable

### PR DESCRIPTION
**Pull request by MVrachev**
Please fill in the fields below to submit a pull request. The more information
that is provided, the better.

**Fixes issue #**: None 

**Description of the changes being introduced by the pull request**:

As per PEP 008 for function and variable names it's
recommended that:

`Function names should be lowercase, with words separated
by underscores as necessary to improve readability.
Variable names follow the same convention as function names.`

I am renaming this variable, because `filelength` are two
separate words merged and it's not so readable.

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by joshuagl — CHANGES_REQUESTED** [review]
Thanks for the submission Martin. 

Please always include a commit message describing the problem being addressed when you submit patches.

**Comment by MVrachev** [comment]
Fixed and in future I will add descriptions in the small patches as well.

**Review by lukpueh — COMMENTED** [review]
What about "upperbound"? :)

**Comment by MVrachev** [comment]
Now when I had pushed a couple of prs I can understand why some of the names are like that.
There are common "merged words" that are used in programming as a whole.

Yes, `upperbound` is a good example.
Can you close this pr for now?

**Comment by lukpueh** [comment]
Thanks, @MVrachev! I definitely appreciate the intention. Let's make sure to keep naming recommendations in mind when adding new code.

**Pull request closed without merging**
