### PR TITLE
docs: fix simple typo, excepion -> exception

### LINKED ISSUE #1262: Fix simple typo: excepion -> exception
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine tests/test_roledb.py.
2. Search for `excepion`.

# Expected Behaviour

1. Should read `exception`.

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR.

https://github.com/timgates42/tuf/pull/new/bugfix_typo_exception

Thanks.

### PR DESCRIPTION
**Pull request by timgates42**
There is a small typo in tests/test_roledb.py.

Closes #1262

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #<ISSUE NUMBER>

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by rzr — APPROVED** [review]

**Review by mnm678 — COMMENTED** [review]
Looks good. Can you fix the DCO?

**Comment by timgates42** [comment]
> Looks good. Can you fix the DCO?

Thanks done

**Comment by rzr** [comment]
Please also check my comments about tick boxes:

https://github.com/theupdateframework/tuf/issues/1262#issuecomment-789771084

**Review by lukpueh — APPROVED** [review]
Thanks for the patch, @timgates42.

> Please also check my comments about tick boxes:

@rzr, we really don't require the check boxes being ticked off.

**Pull request merged**
