### PR TITLE
doc: render tuf logo and favicon on rtd

### PR DESCRIPTION
**Pull request by lukpueh**
Fixes #<ISSUE NUMBER>

**Description of the changes being introduced by the pull request**:
Configure docs to display
- tuf icon as favicon
- tuf horizontal logo (white) in navbar

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by lukpueh** [comment]
See preview here: https://theupdateframework--1829.org.readthedocs.build/en/1829/

**Comment by jku** [comment]
Nice. Some related thoughts:
* Our README seems to use an already deleted logo svg from a completely different repository :)
* We have various images in docs/images/ -- none of these seem to be used currently

Would it make sense to use that existing directory for your new files (and possibly delete the old files)?

**Comment by jku** [comment]
If the source of these is https://github.com/cncf/artwork/tree/master/projects/tuf, we could leave a note mentioning that in the image directory

**Comment by lukpueh** [comment]
Great point! The `images` dir slipped through my sweep in #1745.

I just copied the two images in this PR from the artwork repo (and modified them a little bit). I think it is safe to remove the contents from `images`... and probably the dir itself? I don't know if the `docs` dir becomes much cleaner with the two new images living in the `images` dir (would we also move the `repository-library-design-*.jpg`s?). 

What I currently find more confusing there is the wild mix of general docs (adr, CHANGELOG, etc.) and RTD markup/content/config.

**Review by jku — APPROVED** [review]
That makes sense, thanks.

Leaving for you to merge in case you did want to do the images cleanup here already (fine to leave it for future though)

**Pull request merged**
