### PR TITLE
README: TUF spec version, reference implementation, and other adjustments

### PR DESCRIPTION
**Pull request by awwad**
Explain that this repository is a reference implementation, right at the top of the README.

Also:
- note that this implementation is intended to conform to version
  1.0 of the TUF specification
- draw some distinctions between the TUF design and this ref impl.
- turn the older blurb about TUF into an About-TUF section
- expand that blurb with a link to both an introduction in the repo
  and the TUF website
- make the documentation links a bit more explicit
- shuffle some graphical elements for better appeal
- minor changes like extending some link text

### CODE REVIEW

**Comment by awwad** [comment]
@jhdalek55, can you take a quick peek at this?

**Comment by jhdalek55** [comment]
Sebastien, I don't see a link. Is this the README for the TUF website?


On Tue, Apr 09, 2019 at 05:01 PM, Sebastien Awwad wrote:

@jhdalek55 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jhdalek55&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=vJ0z9j073WrykaiiovNxu1dOT2Kg_SWH-w2tcHIyu2I&s=BL2BsdEisA1kqsx5qXuhcWiRGDR7jG-KdahYOyqJiWE&e=> 
, can you take a quick peek at this?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_theupdateframework_tuf_pull_853-23issuecomment-2D481434318&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=vJ0z9j073WrykaiiovNxu1dOT2Kg_SWH-w2tcHIyu2I&s=4M98kQpz-vAdRBuJWE6fS9t_EeimlMRwM7RJvByK8ZQ&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX1r5QKnK8JnucUSmLAGkkTvz0Sc1ks5vfP-2DtgaJpZM4clnCl&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=vJ0z9j073WrykaiiovNxu1dOT2Kg_SWH-w2tcHIyu2I&s=iVQWQe5IKT9xPlF3mafWPHB6_yNrnruR0_xNPU9nSDc&e=> 
.

**Comment by awwad** [comment]
This is a PR on the TUF reference implementation.  It makes some minor changes to the top of the README.

Link to the PR (also available as a "view it on GitHub" link in the email notification you get for this): https://github.com/theupdateframework/tuf/pull/853

The diff: https://github.com/theupdateframework/tuf/pull/853/files

The rendered result: https://github.com/theupdateframework/tuf/blob/06cdb21efd7def16fd556d5a6ec911bf1dd77ec1/README.md

**Comment by jhdalek55** [comment]
Getting ready to go home. Hope its OK if I look at this after the Uptane
meeting tomorrow. Thanks.

Lois

**Comment by awwad** [comment]
Oh, most definitely.  This is not pressing.

**Comment by awwad** [comment]
@JustinCappos I'm gonna merge this, but it might be worth a quick peek since it's headline info, in case it's sending a message you don't want sent.

**Comment by JustinCappos** [comment]
Looks good. Thanks for the edits.

**Pull request merged**
