### PR TITLE
Fix pylint warnings

### PR DESCRIPTION
**Pull request by MVrachev**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Description of the changes being introduced by the pull request**:

New pylint warnings appeared (for the first time here: https://github.com/theupdateframework/python-tuf/pull/1446/checks?check_run_id=3630842220) with code:
`W0602: Using global for X but no assignment is done (global-variable-not-assigned)`
where X is a global variable.
In the lines pointed by the warnings, "global" was used inside a
function scope in order to enable assignment of the global variable to
a new value in the function.
The reason for these warnings was that pylint noticed we are using
"global" for the variable X inside a function scope without actually
assigning it to a new value.
Overall that was true for the reported cases and I removed the use of
"global", but there were only two cases where pylint reported a
false-positive. Then we were using "global", but pylint didn't
understand there were assignments.
In those cases, I disabled the warnings.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by jku — CHANGES_REQUESTED** [review]
I looked at  a few cases and pylint is correct: those globals are not needed.

`global` is only required if you want to _assign_ to the global variable. mutating the value of that variable does not require global.

**Comment by jku** [comment]
> https://www.programiz.com/python-programming/global-keyword

these third party documentation sites have really variable quality... The whole point of `global` is that _assignment_ to global variables can only work with global, yet this is not mentioned at all. 

I try to find references for this sort of things on python.org (the search engines really fail hard with python searches, always offering this sort of pages before python.org content)

**Comment by MVrachev** [comment]
> I looked at a few cases and pylint is correct: those globals are not needed.
> 
> `global` is only required if you want to _assign_ to the global variable. mutating the value of that variable does not require global.

Updated the pr and removed all but two occurrences of `global` which are false-positives.

> these third party documentation sites have really variable quality... The whole point of global is that assignment to global variables can only work with global, yet this is not mentioned at all.

Yes, you are right. Removed the link from the commit message and pr description.

>I try to find references for this sort of things on python.org (the search engines really fail hard with python searches, always offering this sort of pages before python.org content)

I can't find where on python org globals are mentioned and that's why I won't give a link.

**Review by jku — APPROVED** [review]
> -55 lines, fixes CI

Nice

**Pull request merged**
