### PR TITLE
Start linting tuf/exceptions.py with all linters

### PR DESCRIPTION
**Pull request by MVrachev**
**Description of the changes being introduced by the pull request**:

We are already using tuf/exceptions.py inside
- `tuf/api/metadata.py`
- `tuf/ngclient/__internal__/trusted_metadata_set.py`
- `tuf/ngclient/fetcher.py`
- `tuf/ngclient/updater.py`
- and in our tests using the new code base

This means that we are most likely going to use that
module after we remove the old code.

It makes sense to lint it with the other three
linters besides `mypy` (we already lint tuf/exceptions.py with `mypy`).

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by kairoaraujo — COMMENTED** [review]
We have some commented code as 'Directly instance-repoducing'. Any reason to keep it?

**Comment by jku** [comment]
Alternatively 
* copy exceptions.py to wherever it should live in the future (tuf/api/exceptions.py maybe?)
* remove all of the unused exceptions and cruft from that copy
* make the code actually follow the style guide (and not just pass the linter)
* apply all the fixes you did here
* start importing the new copy in api & ngclient
 
I'm not saying this needs to all happen in one PR, but if you start with making the copy and removing old code, then there's far less code to fix/review and you don't need to deal with pylint disables: the way the PR handles disables almost certainly disabled warnings from all of the old code base, not just exceptions.py

**Comment by MVrachev** [comment]
> Alternatively
> 
> * copy exceptions.py to wherever it should live in the future (tuf/api/exceptions.py maybe?)
> * remove all of the unused exceptions and cruft from that copy
> * make the code actually follow the style guide (and not just pass the linter)
> * apply all the fixes you did here
> * start importing the new copy in api & ngclient
> 
> I'm not saying this needs to all happen in one PR, but if you start with making the copy and removing old code, then there's far less code to fix/review and you don't need to deal with pylint disables: the way the PR handles disables almost certainly disabled warnings from all of the old code base, not just exceptions.py

Yes, I can create a new module in `tuf/api/exceptions.py` and copy the relevant exceptions and follow all the steps.
Will do that in the coming days, but it will be as a side item as I have additional goals for the sprint.

**Comment by MVrachev** [comment]
This pr is superseded by #1725 where I actually add a new `exceptions.py` file as @jku suggested.

**Pull request closed without merging**
