### PR TITLE
Prevent warning message on Repository.status()

### PR DESCRIPTION
**Pull request by joshuagl**
**Description of the changes being introduced by the pull request**:

(from the patch header)

Since e0086d64a59f60b6351fb85250f491e04e04db2e repository_lib warns when metadata is written without signatures.
The Repository class in repository_tool has a status() method which generates the metadata for a repository in order to report various information about the repository metadata, i.e.

'targets' role contains 0 / 1 public keys.
'snapshot' role contains 0 / 1 public keys.
'timestamp' role contains 0 / 1 public keys.
'root' role contains 2 / 2 signatures.
'targets' role contains 0 / 1 signatures.

Since the change to repository_lib above, the output of status() now warns about "Unsigned metadata objects", for example:

'targets' role contains 0 / 1 public keys.
'snapshot' role contains 0 / 1 public keys.
'timestamp' role contains 0 / 1 public keys.
'root' role contains 2 / 2 signatures.
Unsigned metadata object: {'signed': {'version': 1, 'expires': '2021-02-02T17:55:23Z', 'targets': {}, 'delegations': {'keys': {}, 'roles': []}, '_type': 'targets', 'spec_version': '1.0.0'}, 'signatures': []}
'targets' role contains 0 / 1 signatures.

This change restores the output of Repository.status() to not warn about unsigned metadata. Unfortunately it do so at the cost of yet _another_ optional named argument to repository_lib._generate_and_write_metadata(), bringing that function to a total of __16 arguments__, 11 of which are named arguments.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by MVrachev — APPROVED** [review]
The changes look okay, but the solution to add yet another argument to `_generate_and_write_metadata` is far from perfect...

Yet I don't see any better alternative...

**Comment by joshuagl** [comment]
> The changes look okay, but the solution to add yet another argument to `_generate_and_write_metadata` is far from perfect...

Completely agree. 

Some alternatives:
* improve status() as suggested in 
https://github.com/theupdateframework/tuf/issues/955 
* ignore this unless it comes up as part of the refactor efforts

**Comment by sechkova** [comment]
Can I suggest another solution which similarly does not solve the root of the `status()` function problem but does not introduce yet another argument:

```
def _log_status_of_top_level_roles(targets_directory, metadata_directory,
    repository_name, storage_backend):
  ...

  filter = type('', (logging.Filter,), {'filter': staticmethod(lambda r: not r.msg.startswith('Unsigned metadata object'))})
  logger.addFilter(filter)
  ...
  // do whatever the function does
  ...
  logger.removeFilter(filter)
```
 
I haven't thoroughly tested if` logger.removeFilter(filter)` does what its name imply and does not affect the logging outside this function.

**Comment by joshuagl** [comment]
> Can I suggest another solution which similarly does not solve the root of the `status()` function problem but does not introduce yet another argument:

Thank you! I was just coming to close this PR, I do not want to merge it. I filed #1199 to track the issue and discuss cleaner solutions.

**Pull request closed without merging**
