### PR TITLE
Add configurable setting for hashing algorithm used in hashed bin delegations

### PR DESCRIPTION
**Pull request by vladimir-v-diaz**
Fix for issue #438.

### CODE REVIEW

**Comment by vladimir-v-diaz** [comment]
ping @awwad

**Comment by awwad** [comment]
So, it looks like this is specific to hashed bin prefixes, but the comments make it sound like it's a general setting that affects hashing done across TUF. Am I misunderstanding something?

**Comment by vladimir-v-diaz** [comment]
You are correct!  I updated the comment/description to indicate that this setting is now only used to calculate path hash prefixes.

**Comment by awwad** [comment]
Do you think the name of the setting itself should also be more specific (HASH_ALGO_FOR_PATH_HASH_PREFIX or something), or is that getting too paranoid and wordy?

**Comment by awwad** [comment]
No, I think you're fine. This makes sense to me.

**Pull request merged**
