### PR TITLE
Fix pydocstyle D400: first line should end with a period

### PR DESCRIPTION
**Pull request by fridex**
**Description of the changes being introduced by the pull request**:

Make sure the codebase is more compliant with Python's docstring convention. There are more D400 warnings by pydocstyle left. To make this change easier to review, it tries to introduce more straightforward changes to the codebase.

### CODE REVIEW

**Comment by fridex** [comment]
There might be some merge conflicts with https://github.com/theupdateframework/python-tuf/pull/2230, will eventually rebase.

**Review by lukpueh — COMMENTED** [review]
I am all for uniform docstyle. Is there a checker that we can add to our [tox lint run](https://github.com/theupdateframework/python-tuf/blob/216ae641f791623eb09a66c97d7ef857b62757bd/tox.ini#L40)?

**Comment by fridex** [comment]
> I am all for uniform docstyle. Is there a checker that we can add to our [tox lint run](https://github.com/theupdateframework/python-tuf/blob/216ae641f791623eb09a66c97d7ef857b62757bd/tox.ini#L40)?

I used [pydocstyle](https://www.pydocstyle.org/en/stable/), it might be a good candidate. It produces some messages now though so the codebase will need to be adjusted. I can try to find some spare time to help with it if you are open to that.

**Comment by fridex** [comment]
Also, as there are docstyle issues, would it make sense to try fixing them iteratively and later introduce a checker in tox? Or do you prefer to do it the other way - provide checker in tox and possibly let it always succeed until docstrings are compliant?

**Review by jku — CHANGES_REQUESTED** [review]
LGTM but requires a rebase now that the other docs patch is merged

**Comment by jku** [comment]
Closing to clean up the PR list. The change is still welcome though, feel free to reopen if you resolve the conflicts or have comments.

**Pull request closed without merging**
