### PR TITLE
doc: remove duplicate outdated docs

### PR DESCRIPTION
**Pull request by lukpueh**
Fixes #-

**Description of the changes being introduced by the pull request**:
These documents are also hosted on our website and in a better shape too (kudos to @jhdalek55!). There is no need to maintain outdated duplicates.

This patch removes the documents and updates references as needed.

Note, the full history of these docs can be tracked in the old archived website repo and in the new one (filenames may vary in case and extension):

old: https://github.com/theupdateframework/theupdateframework.github.io
new: https://github.com/theupdateframework/theupdateframework.io/tree/master/content

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by mnm678 — APPROVED** [review]
Looks good! I agree that we should point people to one set of up-to-date docs

**Review by jku — APPROVED** [review]
I agree with this, looks good to me.

I wonder if we want to be more explicit in naming TUF as the specification (as in reference _"TUF specification website"_ instead of _"TUF website"_) to make the distinction between the projects (python-tuf and TUF) more clear to new readers? Anyway, it's already good :heavy_check_mark: .

**Comment by lukpueh** [comment]
> I wonder if we want to be more explicit in naming TUF as the specification (as in reference _"TUF specification website"_ instead of _"TUF website"_) to make the distinction between the projects (python-tuf and TUF) more clear to new readers? 

IMO it's okay as it is because python-tuf is the official TUF reference implementation, which makes it less of an autonomous project than other TUF implementations. 🤷

**Comment by jku** [comment]
I was more worried about confusion of type _"a link to TUF website when I'm already on the TUF website, that's just silly"_ -- but I agree it's pretty clear

**Pull request merged**
