### PR TITLE
change utcnow() to now(timezone.utc)

### LINKED ISSUE #2572: datetime.utcnow() is deprecated: stop using it
[utcnow() reference docs](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow): 
> Deprecated since version 3.12: Use [datetime.now()](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) with [UTC](https://docs.python.org/3/library/datetime.html#datetime.UTC) instead.

We have 23 uses of `utcnow()` (mostly tests and examples): all seem straight forward to change to `now()` with utc argument

### PR DESCRIPTION
**Pull request by Mansur908**
Fixes #2572

### CODE REVIEW

**Review by lukpueh — CHANGES_REQUESTED** [review]
Thanks for the patch! Please fix the [linter warnings](https://github.com/theupdateframework/python-tuf/actions/runs/8055330328/job/22004264585?pr=2573#step:5:16) (a few lines are too long now), and sign off your commits (see [DCO check](https://github.com/theupdateframework/python-tuf/pull/2573/checks?check_run_id=22001920416)), otherwise this looks great.

**Comment by lukpueh** [comment]
FYI: You can run `ruff format .` to reformat the long lines

**Comment by jku** [comment]
@Mansur908 if you have any suggestions on how our developer docs could be better to improve this "first PR flow", please comment in #2578

**Review by lukpueh — CHANGES_REQUESTED** [review]
Lint is still failing.  Did you reformat with `ruff`? Btw. you can also [run tests locally](https://theupdateframework.readthedocs.io/en/latest/CONTRIBUTING.html) with `tox`, or  `tox -e lint` to run only the linter.

**Comment by jku** [comment]
This might help you avoid the long lines in tests and examples: Instead of `from datetime import timezone` you could do `from datetime import UTC`  -- I think this alias looks fine for our case and makes usage short.
 
 (but the suggestion to run `tox` after any changes is still good)

**Comment by jku** [comment]
Interesting, this leads to more code issues (serialization and deserialization), I believe:
* `datetime.strptime()` returns naive datetimes (at least for the input we give it): these will then not be compatible with non-naive `datetime.now()` results. We probably should set the timezone to UTZ immediately after reading the naive datetime with strptime
* serializing utc datetimes fails as our code `expires.isoformat() + "Z"` produces gibberish now: we should use an explicit strftime call here

I can have a look at this later but if you want to continue investigating:
* strptime() is used in tuf/api/_payload.py and  tests/generated_data/generate_md.py
* isoformat() is used in tuf/api/_payload.py

**Comment by jku** [comment]
You seem to be allowing changes to your branch (thanks) so I'll push some code fixes on top: they should get this into a ready state

**Review by lukpueh — APPROVED** [review]

**Comment by jku** [comment]
It's a bit of a scary change (with the serialization code tweaks) but I feel pretty good about our test suite... so let's go with this. Thanks @Mansur908

**Pull request merged**
