### PR TITLE
increase default network timeout

### LINKED ISSUE #2442: ngclient: Increase default network timeout
Our default RequestsFetcher sets this default value:

    self.socket_timeout: int = 4  # seconds

sigstore-python patches this:

    # NOTE: We poke into the underlying fetcher here to set a more reasonable timeout.
    # The default timeout is 4 seconds, which can cause spurious timeout errors on
    # CI systems like GitHub Actions (where traffic may be delayed/deprioritized due
    # to network load).
    fetcher = RequestsFetcher()
    fetcher.socket_timeout = 30
    return fetcher

I agree with sigstore-python on this:
* Trying to defend against slow-retrieval attacks is in my opinion impossible in practice, especially for a generic library that could be used in a large number of contexts (it _may_ be possible for a specific application). Even with 4 sec timeout a server could return 1 byte every 3 seconds without triggering this limit: that's a download speed of 30kB per day.
* This theoretical defense is creating real world bugs as documented above

Requests by default does not set a timeout at all:  We should set a default timeout (because indefinite hangs are also not cool) but we should set it without trying to solve slow-retrieval attacks at all: 30 secs sounds good to me.

### PR DESCRIPTION
**Pull request by NicholasTanz**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #2442 

**Description of the changes being introduced by the pull request**:
increase default network timeout from 4 sec to 30 sec. 
**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by NicholasTanz** [comment]
Hey @jku , can you take a look at this PR when you get a chance? thanks

**Review by jku — COMMENTED** [review]
I think this is good, however:
 * There is a class docstring a few lines above this that now documents the wrong default value though -- I think that docstring sentence could be removed altogether so that the value isn't specified in two places (alternativelly the default settings could be made optional constructor arguments at which point their default values are documented by sphinx automatically)
* I'd really like it if the git commit message explained _why_ the change is done. e.g. 
    ```
    trying to defend against slow retrieval attacks in a generic library is impossible 
    but too low timeouts mean failures in high latency systems (like tests running
    on CI).
    ```


I'll leave the approval for someone else as this was my suggestion in the first place -- @lukpueh do you have an opinion?

**Comment by lukpueh** [comment]
Works for me. AFAICS, we already acknowledged the problems with and the resulting lack of slow retrieval protection (#932). So I don't think this patch has any real security implications.

 @NicholasTanz, can you please address @jku's comments? Happy to then approve.

**Comment by NicholasTanz** [comment]
> Works for me. AFAICS, we already acknowledged the problems with and the resulting lack of slow retrieval protection (#932). So I don't think this patch has any real security implications.
> 
> @NicholasTanz, can you please address @jku's comments? Happy to then approve.

yes sounds good, just made the changes @lukpueh

**Review by jku — APPROVED** [review]
Thanks, sorry we dropped the ball for two weeks.

changes look good. I might do a squash merge to get the commit message to be on the relevant commit... Let's see if this project allows that

**Pull request merged**
