### PR TITLE
changed depreciated __metaclass__ to metaclass

### LINKED ISSUE #2196: code uses python 2 "__metaclass__"
python-tuf and securesystemslib both use class variable `__metaclass__ = abc.ABCMeta` to implement abstract classes. This does nothing in Python3 -- classes can be instantiated even if they have that class variable set 

The actually supported methods are
```python
from abc import ABC
class MyABC(ABC)
```
and
```python
from abc import ABCMeta
class MyABC(metaclass=ABCMeta)
```
the latter may be safer (WRT multiple inheritance issues)

### PR DESCRIPTION
**Pull request by aditya-shrivastavv**
Fixes #2196 

In **Python 2**, the `__metaclass__ `attribute is used to specify the `metaclass` for a class. In **Python 3**, this syntax has been _changed_, and the metaclass keyword argument is used instead.

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [x] Tox test had ran successfully.

It's a simple fix which can be verified by anyone

### CODE REVIEW

**Review by jku — CHANGES_REQUESTED** [review]
Thank you. Please have a look at https://docs.python.org/3/library/abc.html for an example of how `metaclass=abc.ABCMeta` keyword works.

You can verify your work by trying this:
```python
from tuf.ngclient import FetcherInterface
FetcherInterface()
```
this should fail as FetcherInterface should be an abstract class that can't be instantiated. Currently it does not fail.

Also, please make sure your commit includes
* message that describes what you are doing
* signed-off-by as described in docs/CONTRIBUTING.md

**Comment by aditya-shrivastavv** [comment]
Hey jku ! 
I am extremely sorry for my mistakes in the PR.
I tried to correct my mistakes in the new commits, please have a look at them.
I am happy to say that have successfully implemented your "Changes Requested" now after running the commands:
```
from tuf.ngclient import FetcherInterface
FetcherInterface()
```
Error generates which says like - abstract class can't be instantiated. please have a look at it.
once again I want to apologize for causing problems. i am still learning, let me know if some more things need to be corrected.

references taken for solving the problems -
1.
https://www.quora.com/Why-do-we-use-abstract-class-Python-if-we-cannot-instantiate-it-it-is-only-inherited-Why-do-we-not-create-another-classes-instead-What-is-the-secret-behind-that-kind-of-classes
2.
https://stackoverflow.com/questions/67498595/in-python-can-an-abstract-class-be-instantiated

**Review by aditya-shrivastavv — COMMENTED** [review]
requested changes - FetcherInterface should be an abstract class that can't be instantiated.
Fixed👍

**Review by jku — CHANGES_REQUESTED** [review]
There is a weird extra commit in this branch: I believe it'll go away if you rebase this branch on current origin/develop (and force push the branch) since the change is in origin/develop already.

The PR message is correct and this code does work but 
* class now derives from class ABC instead of using the keyword "metaclass" like the PR message says
* there's a new unused class variable "metaclass": there's no need for that

**Comment by aditya-shrivastavv** [comment]
i have removed unused line `metaclass = abc.ABCMeta` and inside `class FetcherInterface()`.
I have used `class FetcherInterface(metaclass=abc.ABCMeta):`

I think this solved the problems-
- FetcherInterface should be an abstract class that can't be instantiated.
- class now derives from class ABC instead of using the keyword "metaclass"
- removed new unused class variable "metaclass"

**Review by jku — APPROVED** [review]
Thanks, looks good to me.

I'll merge this as is but as advice for future: with the merge commit that I'll create we will end up with four commits for this two-line change, that's quite a lot. Your 3 commits could have been rebased and squashed into a single commit. Some maintainers don't mind unneeded merges and such but I try to keep the git log readable for future developers .

Thanks for the PR!

**Comment by aditya-shrivastavv** [comment]
thanks jku, I will keep that in mind and be extra carefull next time. thank you for guiding me. Looking forward to more contributions😊

**Pull request merged**
