### PR TITLE
Fixes imports to be vendoring compatible

### LINKED ISSUE #1316: fix imports (to be vendoring compatible) in client refactor
**Current behavior**:
There are imports like `import tuf.settings` which are not compatible with vendoring

**Expected behavior**:
Use `from tuf import settings` (or import specific names from the module if the case requires it)

### PR DESCRIPTION
**Pull request by avelichka**
Fixes #1316

Fixes imports to be vendoring compatible.
Imports like import tuf.settings that are not compatible with vendoring are replaced with from tuf import settings.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by sechkova** [comment]
Thanks for the help, @avelichka!

Can you check the TUF contributor's [guidelines](https://github.com/theupdateframework/tuf/blob/develop/docs/CONTRIBUTORS.rst) so that all checks are successful. 
Let us know if you find anything unclear :)

**Comment by avelichka** [comment]
@sechkova, thank you for sharing the TUF contributor's guidelines!

All checks seem to have passed successfully and I'm looking forward to your comments :)
Thank you in advance for any constructive feedback that you might have regarding the change!

**Review by sechkova — APPROVED** [review]
Thanks! 
LGTM but @jku is the vendoring expert nowadays :)

**Review by jku — APPROVED** [review]
LGTM, thanks

**Pull request merged**
