### PR TITLE
change_target_file_path

### LINKED ISSUE #2304: Delegated path pattern does not match the target path in basic_repo.py
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
In the basic_repo.py example when the metadata is created the target ("basic_repo.py) is used as a Targetfile with a target path set of “manual_repo/basic_repo.py”.

But then when the delegated role is created its path pattern is “*.py” which given the spec should not match to be a delegated role for that target path. 

When the generated metadata files are tested with a client, one cannot fetch the target since there's no match.

References:
* https://theupdateframework.github.io/specification/latest/#pathpattern
* https://github.com/theupdateframework/python-tuf/blob/e7cc34a6a5ed6d5d7e3a81cec328888686f59feb/examples/manual_repo/basic_repo.py#L106
* https://github.com/theupdateframework/python-tuf/blob/e7cc34a6a5ed6d5d7e3a81cec328888686f59feb/examples/manual_repo/basic_repo.py#L283

**Current behavior**:

A client cannot fetch the desired target file since there's no match.

**Expected behavior**:

A client should be able to fetch the desired target file.

### PR DESCRIPTION
**Pull request by h4l0gen**
**Description of the changes being introduced by the pull request**:
changes target path in basic_repo.py

Fixes #2304

### CODE REVIEW

**Comment by h4l0gen** [comment]
IMO, this should works for us, I've used this pattern, as this uses accurate path 
> a [PATHPATTERN](https://theupdateframework.github.io/specification/latest/#pathpattern) of "targets/*.tgz" would match file paths "targets/foo.tgz" and "targets/bar.tgz", but not "targets/foo.txt".

**Review by jku — APPROVED** [review]
This does seem to match the target path that gets used, thanks.

This mergeable as is but if you want you can also try making this comment a little more sensible:
```
#      |----base URL---||-------target path-------|
# e.g. tuf-examples.org/repo_example/basic_repo.py
```
could be something like this to match the actual targetpath in the code

```
#      |--- base artifact URL ---||----- target path -----|
# e.g. tuf-examples.org/artifacts/manual_repo/basic_repo.py
```

**Comment by h4l0gen** [comment]
SGTM, made changes. PTAL

**Comment by jku** [comment]
thanks

**Pull request merged**
