### PR TITLE
tests: Use current python interpreter for sub tests

### PR DESCRIPTION
**Pull request by rzr**
Can be useful to run tests using distro runtimes,
(like python3 on Debian).

Relate-to: https://github.com/theupdateframework/tuf/issues/263
Signed-off-by: Philippe Coval <rzr@users.sf.net>

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #<ISSUE NUMBER>

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by jku** [comment]
Looks correct to me.

The CI failures are some unrelated Windows BS as far as I can tell.

**Review by jku — APPROVED** [review]
Windows test issue filed as #1344.

This PR is fine by me, thanks rzr!

**Comment by jku** [comment]
Hmm, re-running the tests still gives multiple failures here but other PRs are green...

I don't think there's anything wrong with this PR but maybe this actually does end up changing the executable used on CI and this triggers the issues? we could wait until we can test this with some test fixes from #1344...

**Comment by rzr** [comment]
I assumed those were sporadic failures. Since it was on windows and I was unable to reproduce, I didn't look too much in details,
is it related to locks when runing executables ?

**Comment by jku** [comment]
test processes still seem to have open files in the directory we try to remove on test cleanup. Windows is very picky about that -- but unfortunately not reliably so. This change _seems_ to have made it more reliable, or alternatively something changed in github end in the last day. 

The failure I looked at does look like a bug in our tests: I'll try fixing that on monday and we'll see how it affects this.

**Comment by jku** [comment]
Would you mind rebasing this so we see test results with the hopefully fixed tests?

**Comment by jku** [comment]
Thanks!

**Pull request merged**
