### PR TITLE
[Proposal] ADR-0009: document purpose of ref implementation

### PR DESCRIPTION
**Pull request by joshuagl**
**Description of the changes being introduced by the pull request**:

This PR attempts to capture the discussion around the primary purpose of the reference implementation and document a consensus decision.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by MVrachev — APPROVED** [review]
Looks good to me!

**Review by mnm678 — APPROVED** [review]
LGTM

**Review by jku — APPROVED** [review]
The outcome maybe makes it sound like a bigger change in direction than it is? The problem statement does make it pretty clear this is just about helping solve some conflicts not change the overall design direction, so maybe that's not an issue

I'm approving as is but wouldn't object to adding a mention that the implementation should still be an aid to understanding the specification --  good API design can just override that goal if needed

**Review by trishankatdatadog — APPROVED** [review]

**Comment by trishankatdatadog** [comment]
Waiting for @sechkova. After her approval, we can merge.

**Review by sechkova — APPROVED** [review]
LGTM too.

**Pull request merged**
