### PR TITLE
Nominate Teodora to maintainers

### PR DESCRIPTION
**Pull request by joshuagl**
I'd like to propose we make Teodora a maintainer of python-tuf. She has been very active contributing quality implementation to the modern refactor (Metadata API and ngclient) and, more recently, doing a great job with reviewing others' contributions. 

@sechkova please confirm you are willing.

@jku @trishankatdatadog @mnm678 @JustinCappos please cast your vote here.

### CODE REVIEW

**Comment by sechkova** [comment]
Confirmed :)

**Review by JustinCappos — APPROVED** [review]
I approve!  Welcome Teodora!!!

**Review by mnm678 — APPROVED** [review]
Welcome @sechkova!

**Review by jku — APPROVED** [review]
+1, welcome

**Review by trishankatdatadog — APPROVED** [review]

**Comment by trishankatdatadog** [comment]
Finally, what took so long

**Comment by trishankatdatadog** [comment]
Can someone with powers to update repo maintainers make it happen and merge?

**Pull request merged**
