### PR TITLE
[Bugbash] Ignore Bandit Warning B106:hardcoded_password_funcarg in tests

### PR DESCRIPTION
**Pull request by dhavalgshah**

### CODE REVIEW

**Comment by jku** [comment]
Thanks for the contribution. I have nothing against bandit but we don't run it in our Continuous Integration setup at the moment... this means this PR just adds comments that _currently_ provide no value to the project.

Maybe using bandit would be a good idea but that's a case someone would have to make (what are the benefits, can we remove some other tools because bandit does a better job, etc). Before this happens, I think we won't take bandit ignore commits.

**Comment by dhavalgshah** [comment]
Pardon me if I missed some context here. 

Bandit runs as part of `testenv:lint` in tox. And tox is part of CI. So project is using bandit albeit on `tuf` directory and not on `tests`. 

Aside: This PR is part of Kubecon 2022 Bugbash and from this [list of bugs](https://lift.sonatype.com/results/github.com/theupdateframework/python-tuf/01G24KW4TZC7PHFR9RRXG2XX96?s=&t=Bandit%7Chardcoded_password_funcarg). In case this is still unnecessary, maybe someone can tweak how Sonatype Lift scans the repo to align it with project goals.

**Comment by lukpueh** [comment]
> In case this is still unnecessary, maybe someone can tweak how Sonatype Lift scans the repo to align it with project goals.

Sorry to waste your time here. I'm in contact with the Bug Bash organizers. If you want to contribute to python-tuf, I'd appreciate if you picked an issue from our own curated [tracker](https://github.com/theupdateframework/python-tuf/issues), e.g. one that is marked as [“good first issue”](https://github.com/theupdateframework/python-tuf/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

**Comment by jku** [comment]
> Bandit runs as part of testenv:lint in tox. And tox is part of CI.

Oops, sorry about that: I confused bandit with another tool.

You are correct: we do run bandit but only on tuf/ directory, not on tests

**Comment by dhavalgshah** [comment]
> Sorry to waste your time here. I'm in contact with the Bug Bash organizers. If you want to contribute to python-tuf, I'd appreciate if you picked an issue from our own curated [tracker](https://github.com/theupdateframework/python-tuf/issues), e.g. one that is marked as [“good first issue”](https://github.com/theupdateframework/python-tuf/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

I am learning a lot here. Definitely not a waste of time. Looking at #good-first-bugs.

**Pull request closed without merging**
