### PR TITLE
docs: Remove academics files

### PR DESCRIPTION
**Pull request by rzr**
Those generated files are not explicitly under Apache-2.0 licence
and AFAIK they can not be regenerated from missing (latex?) sources.

To avoid licence mixup.
It would help to have those files published elsewhere.
Meanwhile online (Github) links are used.

Debian had to repack the source package to make tarball compliant with DFSG
dispite debian tools are known to be trustworthy,
this extra step would add weakess in the chain of trust

Cleanup done upstream would make distribution safer.

Bug: https://github.com/theupdateframework/tuf/issues/1161
Bug-Debian: https://salsa.debian.org/python-team/packages/tuf/-/merge_requests/11
Relate-to: https://github.com/theupdateframework/tuf/issues/263#issuecomment-835239415
Signed-off-by: Philippe Coval <rzr@users.sf.net>

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

Fixes #<ISSUE NUMBER>

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
I don't have strong feelings, but is there a way to tell Debian package _not_ to include certain files?

**Comment by rzr** [comment]
yes debian has everything to repack archive with files excluded see:

https://salsa.debian.org/python-team/packages/tuf/-/commit/d701faef3d166761993cb0d9595775ee56700e78#adb7f75f79e3bb85eb62912a2904c5d24af878fb_6_6

BTW package in NEW queue: \o/

https://ftp-master.debian.org/new/tuf_0.17.0+dfsg-1.html

**Comment by jku** [comment]
The idea of linking from git to a an older git commit seems fishy to me: Either we want to keep the papers somewhere or we don't.

I wonder if the papers would be a better fit for https://github.com/theupdateframework/specification/ repo?

**Comment by rzr** [comment]
yes That's what I suggested about relocating elsewhere, 
It perfectly makes sense to have them in "specification"
because those files are statics and not tied to sources.
https://github.com/theupdateframework/specification/issues/159

BTW This spec folder can also be packaged for debian unfree if there is any need.

Let me open a PR in spec repo to import theses PDFs and crosslink to this issue.

https://github.com/theupdateframework/specification/pull/160

**Comment by joshuagl** [comment]
Even if we continue to include the PDFs in this repository, we should _not_ include them in the Python packaging either. 

My preference would be that we just keep the PDFs on the website (theupdateframework/theupdateframework.io) and not in the spec or here.

**Comment by rzr** [comment]
Yes duplication it source of confusion, I'll update links

**Review by joshuagl — COMMENTED** [review]
Thanks for this change @rzr !

Any objections @mnm678, @trishankatdatadog ?

**Review by joshuagl — APPROVED** [review]

**Comment by trishankatdatadog** [comment]
Sigh, missed opportunity to install our papers on millions of Debian computers...

**Review by trishankatdatadog — APPROVED** [review]

**Pull request merged**
