### PR TITLE
Support loading external signing keys

### PR DESCRIPTION
**Pull request by danixeee**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #**: -

**Description of the changes being introduced by the pull request**:

This PR shows our general idea on how to provide signatures for _TUF metadata_ files externally. This implementation does not break any current behavior, just allows us to generate signatures on write-only hardware devices (which does not allow exporting private keys) and store them in metadata files. Signatures need to be generated with the same algorithms that are used by TUF. 

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by awwad** [comment]
#864 captures the general response to this PR, outlines the need for external signing or CCID/PIV support, and talks about the paths forward.  Please see that. :)

**Comment by lukpueh** [comment]
@JustinCappos, given that there seems to be a consensus to search for alternative solutions in #864,  do you still want me to review this?

**Comment by danixeee** [comment]
@awwad Just took a look few hours ago. We really appreciate your work on this!

@lukpueh I will make more changes regarding this tomorrow, but probably on our fork. So I guess we can close this one?

**Comment by JustinCappos** [comment]
We want to get to a good solution overall.  We need not take this patch,
but should discuss how to move forward something that solves both
Trishank's issues and those from OLL.

**Comment by awwad** [comment]
@JustinCappos
> We want to get to a good solution overall. We need not take this patch, but should discuss how to move forward something that solves both Trishank's issues and those from OLL.

And that's happening in #864.  (And, @danixeee and team, your input there would be appreciated! 😀)

**Pull request closed without merging**
